spring:
  ## Application Name
  application:
    name: personal-finance-management

  flyway:
    enabled: false

  ## Datasource (Database Connection Configuration)
  datasource:
    url: jdbc:postgresql://localhost:5432/finance_management
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000  # 30 seconds
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 600000
      max-lifetime: 1800000

  ## JPA and Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
        format_sql: true
        default_schema: finance_schema
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  ## Security Configuration (OAuth2 with Keycloak)
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/finance_management

  sql:
    init:
      mode: never

logging:
  level:
    org.springframework.security.oauth2: DEBUG
    org.springframework.security: DEBUG

## Keycloak (OAuth2 Authorization Configuration)
keycloak:
  client-id: finance_management
  auth-server-url: http://localhost:9090
