CREATE TABLE IF NOT EXISTS finance_schema.savings_goal (
                                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                                           name VARCHAR(255),
                                                           target_amount FLOAT(53),
                                                           current_amount FLOAT(53),
                                                           target_date DATE,
                                                           completed BOOLEAN,
                                                           username VARCHAR(255),
                                                           PRIMARY KEY (id)
);